name: Build KittyPrivSystem

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'include/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      
      - name: Compile
        run: |
          gcc -c src/main.c -o main.o -Iinclude
          gcc -c src/utils.c -o utils.o -Iinclude
          gcc -c src/system.c -o system.o -Iinclude
          gcc -c src/file.c -o file.o -Iinclude
          windres src/resource.rc -o resource.o
          gcc -o KittyPrivSystem.exe main.o utils.o system.o file.o resource.o -lgdi32 -lcomctl32 -ladvapi32 -luser32 -lshell32 -lshlwapi
      
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: KittyPrivSystem
          path: KittyPrivSystem.exe
